<a href="https://colab.research.google.com/github/jyotikashyap85399-tech/Image-classification/blob/main/Iterative_imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [5]:
df = np.round(pd.read_csv('/content/drive/MyDrive/Colab Notebooks/50_Startups.csv')[['R&D Spend', 'Administration','Marketing Spend','Profit']]/1000)
np.random.seed(9)
df = df.sample(5)
df

R&D Spend  Administration  Marketing Spend  Profit
21       78.0           154.0            300.0   111.0
37       44.0            51.0            197.0    90.0
2       153.0           101.0            408.0   191.0
14      120.0           157.0            257.0   133.0
44       22.0           155.0             28.0    65.0

In [6]:
df = df.iloc[:,0:-1]
df

R&D Spend  Administration  Marketing Spend
21       78.0           154.0            300.0
37       44.0            51.0            197.0
2       153.0           101.0            408.0
14      120.0           157.0            257.0
44       22.0           155.0             28.0

In [8]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

/tmp/ipython-input-766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/tmp/ipython-input-766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/tmp/ipython-input-766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan


In [9]:
df.head()

R&D Spend  Administration  Marketing Spend
21       78.0           154.0            300.0
37        NaN            51.0            197.0
2       153.0           101.0            408.0
14      120.0             NaN            257.0
44       22.0           155.0              NaN

In [11]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())


In [12]:
df0

R&D Spend  Administration  Marketing Spend
21      78.00          154.00            300.0
37      93.25           51.00            197.0
2      153.00          101.00            408.0
14     120.00          115.25            257.0
44      22.00          155.00            290.5

In [14]:
df1 = df0.copy()

df1.iloc[1,0] = np.nan
df1

R&D Spend  Administration  Marketing Spend
21       78.0          154.00            300.0
37        NaN           51.00            197.0
2       153.0          101.00            408.0
14      120.0          115.25            257.0
44       22.0          155.00            290.5

In [15]:
X = df1.iloc[[0,2,3,4],1:3]
X

Administration  Marketing Spend
21          154.00            300.0
2           101.00            408.0
14          115.25            257.0
44          155.00            290.5

In [16]:
y = df1.iloc[[0,2,3,4],0]
y

21     78.0
2     153.0
14    120.0
44     22.0
Name: R&D Spend, dtype: float64

In [17]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([230.50836125])

In [18]:
df1.iloc[1,0] = 230.50

In [19]:
df1

R&D Spend  Administration  Marketing Spend
21       78.0          154.00            300.0
37      230.5           51.00            197.0
2       153.0          101.00            408.0
14      120.0          115.25            257.0
44       22.0          155.00            290.5

In [20]:
df1.iloc[3,1] = np.nan
df1

R&D Spend  Administration  Marketing Spend
21       78.0           154.0            300.0
37      230.5            51.0            197.0
2       153.0           101.0            408.0
14      120.0             NaN            257.0
44       22.0           155.0            290.5

In [21]:
X = df1.iloc[[0,1,2,4],[0,2]]
X

R&D Spend  Marketing Spend
21       78.0            300.0
37      230.5            197.0
2       153.0            408.0
44       22.0            290.5

In [22]:
y = df1.iloc[[0,1,2,4],1]
y

21    154.0
37     51.0
2     101.0
44    155.0
Name: Administration, dtype: float64

In [23]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([113.55563522])

In [24]:
df1.iloc[3,1] = 113.55

In [25]:
df1

R&D Spend  Administration  Marketing Spend
21       78.0          154.00            300.0
37      230.5           51.00            197.0
2       153.0          101.00            408.0
14      120.0          113.55            257.0
44       22.0          155.00            290.5

In [26]:
df1.iloc[4,-1] = np.nan
df1

R&D Spend  Administration  Marketing Spend
21       78.0          154.00            300.0
37      230.5           51.00            197.0
2       153.0          101.00            408.0
14      120.0          113.55            257.0
44       22.0          155.00              NaN

In [27]:
X = df1.iloc[0:4,0:2]
X

R&D Spend  Administration
21       78.0          154.00
37      230.5           51.00
2       153.0          101.00
14      120.0          113.55

In [28]:
y = df1.iloc[0:4,-1]
y

21    300.0
37    197.0
2     408.0
14    257.0
Name: Marketing Spend, dtype: float64

In [29]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([264.02820283])

In [30]:
df1.iloc[4,-1] = 264.02

In [31]:
df1

R&D Spend  Administration  Marketing Spend
21       78.0          154.00           300.00
37      230.5           51.00           197.00
2       153.0          101.00           408.00
14      120.0          113.55           257.00
44       22.0          155.00           264.02

In [32]:
df1 - df0

R&D Spend  Administration  Marketing Spend
21       0.00             0.0             0.00
37     137.25             0.0             0.00
2        0.00             0.0             0.00
14       0.00            -1.7             0.00
44       0.00             0.0           -26.48

In [33]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan
df2

R&D Spend  Administration  Marketing Spend
21       78.0          154.00           300.00
37        NaN           51.00           197.00
2       153.0          101.00           408.00
14      120.0          113.55           257.00
44       22.0          155.00           264.02

In [35]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([205.53104122])

In [37]:
df2.iloc[3,1] = 205.53

In [38]:
df2.iloc[4,-1] = np.nan
X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([400.7657199])

In [39]:
df2.iloc[4,-1] = 400.76

In [40]:
df2

R&D Spend  Administration  Marketing Spend
21      78.00          154.00           300.00
37     205.53           51.00           197.00
2      153.00          101.00           408.00
14     120.00          205.53           257.00
44      22.00          155.00           400.76

In [41]:
df2 - df1

R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37     -24.97            0.00             0.00
2        0.00            0.00             0.00
14       0.00           91.98             0.00
44       0.00            0.00           136.74