<a href="https://colab.research.google.com/github/jyotikashyap85399-tech/Image-classification/blob/main/NLP_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np
import pandas as pd

In [60]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IMDB Dataset.csv')

In [61]:
df = df.iloc[:10000]

In [62]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [63]:
df.shape

(10000, 2)

**Lowering**

In [64]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [65]:
df['review'] = df['review'].str.lower()

In [66]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. <br /><br />the...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[10000 rows x 2 columns]

**HTML tags removal**

In [67]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [68]:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [69]:
remove_html_tags(text)

' Movie 1 Actor - Aamir Khan Click here to download'

In [70]:
df['review'] = df['review'].apply(remove_html_tags)

In [71]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

**URL removal**

In [72]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [73]:
df['review'] = df['review'].apply(remove_url)

In [74]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[10000 rows x 2 columns]

**punctuation removal**

In [75]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [76]:
exclude = string.punctuation

In [77]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text


In [78]:
df['review'] = df['review'].apply(remove_punc)

In [79]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production the filming tech...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically theres a family where a little boy j...  negative
4     petter matteis love in the time of money is a ...  positive
...                                                 ...       ...
9995  fun entertaining movie about wwii german spy j...  positive
9996  give me a break how can anyone say that this i...  negative
9997  this movie is a bad movie but after watching a...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about filmmaking shows the inten...  positive

[10000 rows x 2 columns]

In [80]:
text = 'string. With. Punctuation?'

In [81]:
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string With Punctuation
9.47713851928711


In [82]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [83]:
df['review'] = df['review'].apply(remove_punc1)

In [84]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production the filming tech...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically theres a family where a little boy j...  negative
4     petter matteis love in the time of money is a ...  positive
...                                                 ...       ...
9995  fun entertaining movie about wwii german spy j...  positive
9996  give me a break how can anyone say that this i...  negative
9997  this movie is a bad movie but after watching a...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about filmmaking shows the inten...  positive

[10000 rows x 2 columns]

In [85]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2*50000)

4.518032073974609


In [86]:
time1/time2

2.0976253298153034

In [87]:
df['review'][5]

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

In [88]:
remove_punc1(df['review'][5])

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

**chat words**

In [89]:
chat_words = {
    'FYI': 'For Your Information',
    'IMHO': 'In My Humble Opinion',
    'LOL': 'Laughing Out Loud',
    'BRB': 'Be Right Back',
    'BFF': 'Best Friends Forever'
}

In [90]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [91]:
df['review'] = df['review'].apply(chat_conversion)

In [92]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production the filming tech...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically theres a family where a little boy j...  negative
4     petter matteis love in the time of money is a ...  positive
...                                                 ...       ...
9995  fun entertaining movie about wwii german spy j...  positive
9996  give me a break how can anyone say that this i...  negative
9997  this movie is a bad movie but after watching a...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about filmmaking shows the inten...  positive

[10000 rows x 2 columns]

In [93]:
chat_conversion('IMHO he is the best')

'In My Humble Opinion he is the best'

In [94]:
chat_conversion('FYI delhi is the capital of india')

'For Your Information delhi is the capital of india'

**Stop word removal**

In [95]:
from nltk.corpus import stopwords

In [96]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [97]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [98]:
#Taking longer time to run
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [99]:
#For faster
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

# Convert stopwords to a set once
stop_words = set(stopwords.words('english'))

# Fast remove stopwords function
def remove_stopwords_fast(text):
    try:
        return " ".join([word for word in text.split() if word.lower() not in stop_words])
    except:
        return text


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [100]:
df['review'] = df['review'].apply(remove_stopwords_fast)

In [101]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [102]:
df.head()

review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

**Removing emojis**

In [103]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [104]:
df['review'] = df['review'].apply(remove_emoji)

In [105]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production filming technique ...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically theres family little boy jake thinks...  negative
4     petter matteis love time money visually stunni...  positive
...                                                 ...       ...
9995  fun entertaining movie wwii german spy julie a...  positive
9996  give break anyone say good hockey movie know m...  negative
9997  movie bad movie watching endless series bad ho...  negative
9998  movie probably made entertain middle school ea...  negative
9999  smashing film filmmaking shows intense strange...  positive

[10000 rows x 2 columns]

In [106]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

Using the split function

In [107]:
# word tokenization example
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [108]:
# sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [109]:
# Problems with split function
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [110]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

**NLTK Tokenization**

In [111]:
from nltk.tokenize import word_tokenize,sent_tokenize

 **Tokenization using spacy**

**Stemming**

In [112]:
from nltk.stem.porter import PorterStemmer

In [113]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [114]:
df['review'] = df['review'].apply(stem_words)

In [115]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

**Lemmatization**

In [116]:
import nltk
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_word(text):
    word_tokens = text.split()
    lemmas = [lemmatizer.lemmatize(word, pos ='v') for word in word_tokens]
    return lemmas



In [117]:
df['review'] = df['review'].apply(lemmatize_word)

In [118]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [119]:
df

review sentiment
0     [one, review, mention, watch, 1, oz, episod, y...  positive
1     [wonder, littl, product, film, techniqu, unass...  positive
2     [think, wonder, way, spend, time, hot, summer,...  positive
3     [basic, there, famili, littl, boy, jake, think...  negative
4     [petter, mattei, love, time, money, visual, st...  positive
...                                                 ...       ...
9995  [fun, entertain, movi, wwii, german, spi, juli...  positive
9996  [give, break, anyon, say, good, hockey, movi, ...  negative
9997  [movi, bad, movi, watch, endless, seri, bad, h...  negative
9998  [movi, probabl, make, entertain, middl, school...  negative
9999  [smash, film, filmmak, show, intens, strang, r...  positive

[10000 rows x 2 columns]

ohe, bag of word tf idf

In [120]:
df['review'] = df['review'].apply(lambda x: " ".join(x))
df.duplicated().sum()

np.int64(17)

In [121]:
df.drop_duplicates(inplace=True)

In [122]:
df.duplicated().sum()

np.int64(0)

In [123]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = df['sentiment']
y = encoder.fit_transform(y)

In [124]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [125]:
from sklearn.model_selection import train_test_split
X = df['review']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [126]:
X_train.shape

(7986,)

**Bag of words**

In [127]:

from sklearn.feature_extraction.text import CountVectorizer

In [128]:
cv = CountVectorizer()

In [129]:
X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()
X_train_bow.shape

(7986, 54935)

**Using ngrams**

In [130]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [131]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6459689534301453

In [132]:
confusion_matrix(y_test,y_pred)

array([[685, 267],
       [440, 605]])

In [133]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8382573860791187

In [135]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8342513770655984

**Using TfIdf**

In [136]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [138]:
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test)

In [139]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8387581372058087

 **using Word2Vec**

In [142]:
import gensim
from gensim.models import Word2Vec,KeyedVectors

In [141]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 54.8 MB/s eta 0:00:00


In [143]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [145]:
model.build_vocab(df['review'])

In [147]:
model.train(df['review'], total_examples=model.corpus_count, epochs=model.epochs)

(6496717, 37017360)

In [148]:
len(model.wv.index_to_key)

82

In [153]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    if not doc:  # Handle empty list case
        return np.zeros(model.vector_size)
    return np.mean(model.wv[doc], axis=0)

In [150]:
document_vector(df['review'].values[0])

array([-0.47445196, -0.35534453, -0.8450753 , -1.8577131 ,  1.6824379 ,
        1.534366  , -0.42549106, -1.0047858 ,  0.92356384,  0.4176279 ,
       -0.802599  ,  0.6520567 , -1.2164456 , -1.1763697 , -1.0031675 ,
        1.1550694 , -1.5194091 ,  1.3104421 , -0.33477843,  0.18191068,
        1.0527307 , -0.24858758,  1.5110711 ,  1.5701063 , -0.47444865,
       -0.23505412,  2.2215767 , -1.8601326 ,  0.0224156 ,  0.20301259,
        0.90573245, -0.67174983, -0.21514764,  0.8347896 , -0.63239354,
        0.03373199, -0.36798188,  0.46074808,  0.543455  ,  0.4517794 ,
       -1.3663269 ,  0.8867669 ,  0.6675533 , -0.70305854,  0.29836786,
        1.1525574 ,  0.49358732, -0.5824626 , -0.14471632,  0.67049026,
       -0.1594896 ,  0.61290765,  0.6968803 , -0.6548282 ,  0.6379863 ,
        0.11472248,  0.09388594,  0.61071986, -0.96345437,  0.23116434,
        0.2846014 , -0.15145952, -0.7398412 , -0.94694483, -0.14942741,
       -1.133259  ,  0.18139565, -0.6704168 ,  0.27164313, -0.12

In [154]:
from tqdm import tqdm

In [155]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [00:02<00:00, 4973.21it/s]


In [156]:
X = np.array(X)

In [157]:
X[0]

array([-0.47445196, -0.35534453, -0.84507531, -1.8577131 ,  1.6824379 ,
        1.53436601, -0.42549106, -1.00478578,  0.92356384,  0.4176279 ,
       -0.80259901,  0.65205669, -1.21644557, -1.17636967, -1.00316751,
        1.15506935, -1.51940906,  1.31044209, -0.33477843,  0.18191068,
        1.05273068, -0.24858758,  1.51107109,  1.57010627, -0.47444865,
       -0.23505412,  2.22157669, -1.86013258,  0.0224156 ,  0.20301259,
        0.90573245, -0.67174983, -0.21514764,  0.83478957, -0.63239354,
        0.03373199, -0.36798188,  0.46074808,  0.543455  ,  0.4517794 ,
       -1.36632693,  0.88676691,  0.66755331, -0.70305854,  0.29836786,
        1.15255737,  0.49358732, -0.58246261, -0.14471632,  0.67049026,
       -0.1594896 ,  0.61290765,  0.69688028, -0.65482819,  0.6379863 ,
        0.11472248,  0.09388594,  0.61071986, -0.96345437,  0.23116434,
        0.28460139, -0.15145952, -0.73984122, -0.94694483, -0.14942741,
       -1.13325906,  0.18139565, -0.67041677,  0.27164313, -0.12

In [159]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [160]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [161]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [162]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [163]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.5718577866800201