<a href="https://colab.research.google.com/github/jyotikashyap85399-tech/Image-classification/blob/main/pytorch_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import torch
x = torch.tensor(6.7)
y = torch.tensor(0.0)
w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [74]:
#binary cross entropy loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8
    prediction = torch.clamp(prediction, epsilon,1-epsilon)
    return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))


In [75]:
z = w*x+b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy_loss(y_pred, y)

In [76]:
loss

tensor(6.7012)

In [77]:
dloss_dy_pred = (y_pred-y)/(y_pred*(1-y_pred))
dy_pred_dz = y_pred*(1-y_pred)
dz_dw = x
dz_db = 1
dL_dw = dloss_dy_pred*dy_pred_dz*dz_dw
dL_db = dloss_dy_pred*dy_pred_dz*dz_db

In [78]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [79]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [80]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [81]:
w

tensor(1., requires_grad=True)

In [82]:
b

tensor(0., requires_grad=True)

In [83]:
z = w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [84]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [85]:
loss = binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [86]:
loss.backward()

In [87]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [88]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)

In [89]:
x

tensor([1., 2., 3.], requires_grad=True)

In [90]:
y = (x**2).mean()

In [91]:
y.backward()

In [92]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [93]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [94]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [95]:
y.backward(retain_graph=True)

In [96]:
x.grad

tensor(4.)

In [97]:
x.grad.zero_()

tensor(0.)

In [98]:
# y.backward() # Remove or comment out this line

In [99]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [100]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [101]:
df.shape

(569, 33)

In [102]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [103]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [104]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [105]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [106]:
X_train

array([[ 2.00633724,  1.3532272 ,  2.17895815, ...,  2.10784766,
         0.06666314,  0.8343563 ],
       [-0.67027668, -0.61304378, -0.69362815, ..., -0.6517319 ,
        -2.00040568, -0.59330306],
       [ 1.18097529,  0.59427462,  1.10194864, ..., -0.3207678 ,
        -0.88449425, -1.03627246],
       ...,
       [-0.46393619, -0.99368769, -0.52997319, ..., -1.08783281,
         0.01910527, -0.90930671],
       [ 1.39312819,  0.15992023,  1.24919603, ...,  0.24140755,
        -0.54819217, -1.49955638],
       [ 0.9688224 ,  0.87917374,  0.83269626, ..., -0.46224636,
        -0.74351913, -1.06053703]])

In [107]:
y_train

563    M
136    B
197    M
252    M
495    B
      ..
418    B
322    B
241    B
277    M
261    M
Name: diagnosis, Length: 455, dtype: object

In [108]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [109]:
y_train

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,

In [110]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [111]:
X_train_tensor.shape

torch.Size([455, 30])

In [112]:
class MySimpleNN():
  def __init__(self, X):
    self.weights  = torch.rand(X.shape[1], 1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor*torch.log(y_pred) +(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss


In [113]:
learning_rate = 0.1
epochs = 25

In [114]:
#create model
model = MySimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
#forward pass
  y_pred = model.forward(X_train_tensor)
  print(y_pred)

#loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)


  loss.backward()

#backward pass
  with torch.no_grad():
    model.weights -= learning_rate*model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')




Streaming output truncated to the last 5000 lines.
        [2.5967e-03],
        [5.8891e-01],
        [1.1521e-02],
        [3.2009e-02],
        [1.4229e-01],
        [8.5660e-01],
        [9.6674e-01],
        [2.7862e-01],
        [1.8701e-03],
        [9.9826e-01],
        [5.0790e-02],
        [7.7692e-01],
        [5.0423e-02],
        [2.0729e-01],
        [9.0703e-01],
        [7.5139e-01],
        [1.6810e-02],
        [4.1403e-02],
        [1.6333e-02],
        [8.3917e-02],
        [1.7000e-02],
        [7.9752e-02],
        [8.2410e-01],
        [3.9591e-02],
        [9.7397e-01],
        [7.8323e-01],
        [9.5261e-01],
        [9.8463e-01],
        [9.8712e-01],
        [9.4994e-01],
        [2.9470e-01],
        [1.4586e-01],
        [9.3786e-01],
        [1.1083e-02],
        [9.4451e-02],
        [9.9998e-01],
        [9.9410e-01],
        [9.9193e-01],
        [4.4333e-03],
        [4.4513e-02],
        [9.9435e-01],
        [4.8850e-02],
        [8.7193e-01],
   

In [115]:
model.weights

tensor([[ 0.4385],
        [ 0.6234],
        [-0.1811],
        [ 0.4142],
        [ 0.3041],
        [-0.3123],
        [ 0.1002],
        [ 0.0614],
        [ 0.3571],
        [ 0.1326],
        [-0.2472],
        [ 0.1796],
        [-0.3031],
        [-0.0085],
        [ 0.3892],
        [ 0.2213],
        [ 0.4576],
        [-0.1758],
        [ 0.1917],
        [-0.0407],
        [ 0.3502],
        [-0.1006],
        [-0.3416],
        [-0.2402],
        [-0.0258],
        [-0.2794],
        [-0.2943],
        [ 0.1641],
        [ 0.2676],
        [ 0.0087]], dtype=torch.float64, requires_grad=True)

In [118]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5123114585876465
