<a href="https://colab.research.google.com/github/jyotikashyap85399-tech/Image-classification/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
    nn.Linear(num_features, 3),
    nn.ReLU(),
    nn.Linear(3,1),
    nn.Sigmoid()
    )
  def forward(self, features):

    out = self.network(features)

    return out

In [3]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

model(features)

tensor([[0.5074],
        [0.5242],
        [0.5617],
        [0.4892],
        [0.4988],
        [0.5309],
        [0.5292],
        [0.4868],
        [0.5452],
        [0.4807]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear.weight

Parameter containing:
tensor([[ 0.0032, -0.4308,  0.2268, -0.1167, -0.3226]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([0.3035], requires_grad=True)

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00